### ISSUE TITLE
Training on custom datasets

### ISSUE THREAD

**Issue by Double-zh** [meyerls/FruitNeRF#10]
**Hello, when I tried to train my own dataset, a problem occurred. Could you please help me find out the reason? Thank you.**

**(fruit) catas@catas:~/FruitNeRF/data/1/output$ ns-train fruit_nerf  --data /home/catas/FruitNeRF/data/1/output/ --output-dir /home/catas/FruitNeRF/data/1/train**

/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value FruitPipelineConfig:
    _target: <class 'fruit_nerf.fruit_pipeline.FruitPipeline'>
    datamanager: FruitDataManagerConfig:
        _target: <class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>
        data: None
        camera_optimizer: CameraOptimizerConfig:
            _target: <class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>
            mode: SO3xR3
            position_noise_std: 0.0
            orientation_noise_std: 0.0
            optimizer: AdamOptimizerConfig:
                _target: <class 'torch.optim.adam.Adam'>
                lr: 0.0006
                eps: 1e-08
                max_norm: None
                weight_decay: 0.01
            scheduler: ExponentialDecaySchedulerConfig:
                _target: <class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>
                lr_pre_warmup: 1e-08
                lr_final: 6e-06
                warmup_steps: 0
                max_steps: 200000
                ramp: cosine
            param_group: camera_opt
        masks_on_gpu: None
        dataparser: FruitNerfDataParserConfig:
            _target: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>
            data: .
            scale_factor: 1.0
            downscale_factor: None
            scene_scale: 1.0
            orientation_method: up
            center_method: poses
            auto_scale_poses: True
            train_split_fraction: 0.9
        train_num_rays_per_batch: 4096
        train_num_images_to_sample_from: -1
        train_num_times_to_repeat_images: -1
        eval_num_rays_per_batch: 4096
        eval_num_images_to_sample_from: -1
        eval_num_times_to_repeat_images: -1
        eval_image_indices: [0]
        collate_fn: <function nerfstudio_collate at 0x7f20336d2c10>
        camera_res_scale_factor: 1.0
        patch_size: 1
    model: FruitNerfModelConfig:
        _target: <class 'fruit_nerf.fruit_nerf.FruitModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 32768
        prompt: None
        near_plane: 0.05
        far_plane: 1000.0
        background_color: last_sample
        hidden_dim: 64
        hidden_dim_color: 64
        hidden_dim_transient: 64
        num_levels: 16
        base_res: 16
        max_res: 2048
        log2_hashmap_size: 19
        features_per_level: 2
        num_proposal_samples_per_ray: [256
        96]
        num_nerf_samples_per_ray: 48
        proposal_update_every: 5
        proposal_warmup: 5000
        num_proposal_iterations: 2
        use_same_proposal_network: False
        proposal_net_args_list: [{'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False}, {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}]
        proposal_initial_sampler: piecewise
        interlevel_loss_mult: 1.0
        distortion_loss_mult: 0.002
        orientation_loss_mult: 0.0001
        pred_normal_loss_mult: 0.001
        use_proposal_weight_anneal: True
        use_average_appearance_embedding: True
        proposal_weights_anneal_slope: 10.0
        proposal_weights_anneal_max_num_iters: 1000
        use_single_jitter: True
        predict_normals: False
        disable_scene_contraction: False
        use_gradient_scaling: False
        implementation: tcnn
        appearance_embed_dim: 32
        semantic_loss_weight: 1.0
        pass_semantic_gradients: False
        num_layers_semantic: 2
        hidden_dim_semantics: 64
        geo_feat_dim: 15 has type <class 'fruit_nerf.fruit_pipeline.FruitPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/tyro/_fields.py:1066: UserWarning: Mutable type <class 'nerfstudio.data.datamanagers.base_datamanager.DataManagerConfig'> is used as a default value for `datamanager`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.data.datamanagers.base_datamanager.DataManagerConfig'> as frozen.
  warnings.warn(
/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/tyro/_fields.py:1066: UserWarning: Mutable type <class 'nerfstudio.models.base_model.ModelConfig'> is used as a default value for `model`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.models.base_model.ModelConfig'> as frozen.
  warnings.warn(
/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/tyro/_resolver.py:455: UserWarning: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerfDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>]
  warnings.warn(
/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value FruitPipelineConfig:
    _target: <class 'fruit_nerf.fruit_pipeline.FruitPipeline'>
    datamanager: FruitDataManagerConfig:
        _target: <class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>
        data: None
        camera_optimizer: CameraOptimizerConfig:
            _target: <class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>
            mode: SO3xR3
            position_noise_std: 0.0
            orientation_noise_std: 0.0
            optimizer: RAdamOptimizerConfig:
                _target: <class 'torch.optim.radam.RAdam'>
                lr: 0.0006
                eps: 1e-08
                max_norm: None
                weight_decay: 0.001
            scheduler: ExponentialDecaySchedulerConfig:
                _target: <class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>
                lr_pre_warmup: 1e-08
                lr_final: None
                warmup_steps: 0
                max_steps: 10000
                ramp: cosine
            param_group: camera_opt
        masks_on_gpu: None
        dataparser: FruitNerfDataParserConfig:
            _target: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>
            data: .
            scale_factor: 1.0
            downscale_factor: None
            scene_scale: 1.0
            orientation_method: up
            center_method: poses
            auto_scale_poses: True
            train_split_fraction: 0.9
        train_num_rays_per_batch: 1024
        train_num_images_to_sample_from: -1
        train_num_times_to_repeat_images: -1
        eval_num_rays_per_batch: 512
        eval_num_images_to_sample_from: -1
        eval_num_times_to_repeat_images: -1
        eval_image_indices: [0]
        collate_fn: <function nerfstudio_collate at 0x7f20336d2c10>
        camera_res_scale_factor: 1.0
        patch_size: 1
    model: FruitNerfModelConfig:
        _target: <class 'fruit_nerf.fruit_nerf.FruitModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 32768
        prompt: None
        near_plane: 0.05
        far_plane: 1000.0
        background_color: last_sample
        hidden_dim: 128
        hidden_dim_color: 128
        hidden_dim_transient: 64
        num_levels: 16
        base_res: 16
        max_res: 4096
        log2_hashmap_size: 21
        features_per_level: 2
        num_proposal_samples_per_ray: [512
        256]
        num_nerf_samples_per_ray: 128
        proposal_update_every: 5
        proposal_warmup: 5000
        num_proposal_iterations: 2
        use_same_proposal_network: False
        proposal_net_args_list: [{'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False}, {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}]
        proposal_initial_sampler: piecewise
        interlevel_loss_mult: 1.0
        distortion_loss_mult: 0.002
        orientation_loss_mult: 0.0001
        pred_normal_loss_mult: 0.001
        use_proposal_weight_anneal: True
        use_average_appearance_embedding: True
        proposal_weights_anneal_slope: 10.0
        proposal_weights_anneal_max_num_iters: 5000
        use_single_jitter: True
        predict_normals: False
        disable_scene_contraction: False
        use_gradient_scaling: False
        implementation: tcnn
        appearance_embed_dim: 128
        semantic_loss_weight: 1.0
        pass_semantic_gradients: False
        num_layers_semantic: 3
        hidden_dim_semantics: 128
        geo_feat_dim: 30 has type <class 'fruit_nerf.fruit_pipeline.FruitPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value FruitPipelineConfig:
    _target: <class 'fruit_nerf.fruit_pipeline.FruitPipeline'>
    datamanager: FruitDataManagerConfig:
        _target: <class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>
        data: None
        camera_optimizer: CameraOptimizerConfig:
            _target: <class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>
            mode: SO3xR3
            position_noise_std: 0.0
            orientation_noise_std: 0.0
            optimizer: RAdamOptimizerConfig:
                _target: <class 'torch.optim.radam.RAdam'>
                lr: 0.0006
                eps: 1e-08
                max_norm: None
                weight_decay: 0.001
            scheduler: ExponentialDecaySchedulerConfig:
                _target: <class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>
                lr_pre_warmup: 1e-08
                lr_final: 6e-05
                warmup_steps: 0
                max_steps: 50000
                ramp: cosine
            param_group: camera_opt
        masks_on_gpu: None
        dataparser: FruitNerfDataParserConfig:
            _target: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>
            data: .
            scale_factor: 1.0
            downscale_factor: None
            scene_scale: 1.0
            orientation_method: up
            center_method: poses
            auto_scale_poses: True
            train_split_fraction: 0.9
        train_num_rays_per_batch: 2048
        train_num_images_to_sample_from: -1
        train_num_times_to_repeat_images: -1
        eval_num_rays_per_batch: 512
        eval_num_images_to_sample_from: -1
        eval_num_times_to_repeat_images: -1
        eval_image_indices: [0]
        collate_fn: <function nerfstudio_collate at 0x7f20336d2c10>
        camera_res_scale_factor: 1.0
        patch_size: 1
    model: FruitNerfModelConfig:
        _target: <class 'fruit_nerf.fruit_nerf.FruitModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 32768
        prompt: None
        near_plane: 0.05
        far_plane: 1000.0
        background_color: last_sample
        hidden_dim: 256
        hidden_dim_color: 256
        hidden_dim_transient: 64
        num_levels: 16
        base_res: 16
        max_res: 8192
        log2_hashmap_size: 21
        features_per_level: 2
        num_proposal_samples_per_ray: [512
        512]
        num_nerf_samples_per_ray: 64
        proposal_update_every: 5
        proposal_warmup: 5000
        num_proposal_iterations: 2
        use_same_proposal_network: False
        proposal_net_args_list: [{'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 512, 'use_linear': False}, {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 7, 'max_res': 2048, 'use_linear': False}]
        proposal_initial_sampler: piecewise
        interlevel_loss_mult: 1.0
        distortion_loss_mult: 0.002
        orientation_loss_mult: 0.0001
        pred_normal_loss_mult: 0.001
        use_proposal_weight_anneal: True
        use_average_appearance_embedding: True
        proposal_weights_anneal_slope: 10.0
        proposal_weights_anneal_max_num_iters: 5000
        use_single_jitter: True
        predict_normals: False
        disable_scene_contraction: False
        use_gradient_scaling: False
        implementation: tcnn
        appearance_embed_dim: 32
        semantic_loss_weight: 1.0
        pass_semantic_gradients: False
        num_layers_semantic: 3
        hidden_dim_semantics: 128
        geo_feat_dim: 30 has type <class 'fruit_nerf.fruit_pipeline.FruitPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
[17:17:56] Using --data alias for --data.pipeline.datamanager.data                                          train.py:231
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=PosixPath('/home/catas/FruitNeRF/data/1/train'),
    method_name='fruit_nerf',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-08-28_171756',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=32768,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=90
    ),
    pipeline=FruitPipelineConfig(
        _target=<class 'fruit_nerf.fruit_pipeline.FruitPipeline'>,
        datamanager=FruitDataManagerConfig(
            _target=<class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>,
            data=PosixPath('/home/catas/FruitNeRF/data/1/output'),
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                position_noise_std=0.0,
                orientation_noise_std=0.0,
                optimizer=AdamOptimizerConfig(
                    _target=<class 'torch.optim.adam.Adam'>,
                    lr=0.0006,
                    eps=1e-08,
                    max_norm=None,
                    weight_decay=0.01
                ),
                scheduler=ExponentialDecaySchedulerConfig(
                    _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                    lr_pre_warmup=1e-08,
                    lr_final=6e-06,
                    warmup_steps=0,
                    max_steps=200000,
                    ramp='cosine'
                ),
                param_group='camera_opt'
            ),
            masks_on_gpu=None,
            dataparser=FruitNerfDataParserConfig(
                _target=<class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>,
                data=PosixPath('.'),
                scale_factor=1.0,
                downscale_factor=None,
                scene_scale=1.0,
                orientation_method='up',
                center_method='poses',
                auto_scale_poses=True,
                train_split_fraction=0.9
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7f20336d2c10>,
            camera_res_scale_factor=1.0,
            patch_size=1
        ),
        model=FruitNerfModelConfig(
            _target=<class 'fruit_nerf.fruit_nerf.FruitModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_average_appearance_embedding=True,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32,
            semantic_loss_weight=1.0,
            pass_semantic_gradients=False,
            num_layers_semantic=2,
            hidden_dim_semantics=64,
            geo_feat_dim=15
        )
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.0001,
                warmup_steps=0,
                max_steps=200000,
                ramp='cosine'
            )
        },
        'fields': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.0001,
                warmup_steps=0,
                max_steps=200000,
                ramp='cosine'
            )
        }
    },
    vis='viewer',
    data=PosixPath('/home/catas/FruitNeRF/data/1/output'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    steps_per_save=2000,
    steps_per_eval_batch=500,
    steps_per_eval_image=500,
    steps_per_eval_all_images=25000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps=1
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
           Saving config to:                                                                    experiment_config.py:134
           /home/catas/FruitNeRF/data/1/train/output/fruit_nerf/2024-08-28_171756/config.yml                            
           Saving checkpoints to:                                                                         trainer.py:135
           /home/catas/FruitNeRF/data/1/train/output/fruit_nerf/2024-08-28_171756/nerfstudio_models                     
           Auto image downscale factor of 2                                                  fruitnerf_dataparser.py:320
Traceback (most recent call last):
  File "/home/catas/anaconda3/envs/fruit/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 261, in entrypoint
    main(
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 246, in main
    launch(
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 148, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/home/catas/FruitNeRF/fruit_nerf/fruit_pipeline.py", line 103, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/home/catas/FruitNeRF/fruit_nerf/data/fruit_datamanager.py", line 153, in __init__
    super().__init__(
  File "/home/catas/anaconda3/envs/fruit/lib/python3.8/site-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 399, in __init__
    self.eval_dataset = self.create_eval_dataset()
  File "/home/catas/FruitNeRF/fruit_nerf/data/fruit_datamanager.py", line 183, in create_eval_dataset
    return FruitDataset(
  File "/home/catas/FruitNeRF/fruit_nerf/data/fruit_dataset.py", line 72, in __init__
    assert "semantics" in dataparser_outputs.metadata.keys() and isinstance(self.metadata["semantics"],
**AssertionError: No semantic istance could be found! Is a semantic folder included in the input folder and transform.json file?**

**(fruit) catas@catas:~/FruitNeRF/data/1/output$ ls
colmap  images  images_2  images_4  images_8  semantics  semantics_2  semantics_4  semantics_8  transforms.json**
![1724837250238](https://github.com/user-attachments/assets/19cb9791-a5f6-43ea-9122-c0985e1d8784)

**Comment by meyerls** [comment]
Do the images in the semantic folder have .jpg as a file ending?

**Comment by Double-zh** [comment]
> Do the images in the semantic folder have .jpg as a file ending?

Yes. The images in the folder are in .jpg file format.
![image](https://github.com/user-attachments/assets/b73665cc-83d9-400e-96cb-440365d8fea9)

**Comment by meyerls** [comment]
I found the error. It is if all images are selected for training and the eval image set is empty. The solution is to set the parameters `--pipeline.datamanager.dataparser.train-split-fraction 0.99` or set the dataparser property in the [config_file](https://github.com/meyerls/FruitNeRF/blob/0cc6039b2fb4f278d78d88123cf25a0c0850307f/fruit_nerf/fruit_nerf_config.py#L36):

            datamanager=FruitDataManagerConfig(
                dataparser=FruitNerfDataParserConfig(train_split_fraction=0.99),
                train_num_rays_per_batch=4096 * 2,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(
                    mode="SO3xR3",
                    optimizer=RAdamOptimizerConfig(lr=6e-4, eps=1e-8, weight_decay=1e-3),
                ),
            ),`
`

**Comment by liuyi0316** [comment]
hello, i faced the same error, do you know how to address it now?

**Comment by cwh01** [comment]
hello,What are your experimental results?
