### ISSUE TITLE
Is it possible to use last version of nerfstudio?

### ISSUE THREAD

**Issue by johnnynunez** [meyerls/FruitNeRF#11]
I'm porting all environment for jetson agx orin. It comes with cuda 12.2 so most of the library need the last version like colmap 3.10 etc.
I have all packages ready and now I'm building nerfstudio.
So, could you update for nerfstudio v1.1.4 https://github.com/nerfstudio-project/nerfstudio/releases/tag/v1.1.4?  

https://github.com/johnnynunez/jetson-containers/tree/nerf

**Comment by meyerls** [comment]
Unfortunately I won't have the time to upgrade the code to nerfstudio v1.1.4. But if you upgrade it yourself feel free to contribute to this repository. 

I would guess downgrading the Cuda version to 11 would enable you to use the current version.

**Comment by johnnynunez** [comment]
> Unfortunately I won't have the time to upgrade the code to nerfstudio v1.1.4. But if you upgrade it yourself feel free to contribute to this repository. 
> 
> 
> 
> I would guess downgrading the Cuda version to 11 would enable you to use the current version.

I will try🙌🏻

**Comment by johnnynunez** [comment]
> Unfortunately I won't have the time to upgrade the code to nerfstudio v1.1.4. But if you upgrade it yourself feel free to contribute to this repository.
> 
> I would guess downgrading the Cuda version to 11 would enable you to use the current version.

https://github.com/meyerls/FruitNeRF/pull/13

**Comment by johnnynunez** [comment]
enjoy @meyerls  https://www.jetson-ai-lab.com/nerf.html

**Comment by meyerls** [comment]
Thank you very much, cool work! I will post a link on the readme :)
