### ISSUE TITLE
Run on the "Point Cloud Clustering / Fruit Counting" part of the pipeline

### ISSUE THREAD

**Issue by Double-zh** [meyerls/FruitNeRF#12]
For Apple_GT_1024x1024_300 = {
"path": "/path/2/extracted/pcd/semantic_colormap.ply",
"remove_outliers_nb_points": 200, # Clean pcd
"remove_outliers_radius": 0.01, # Clean pcd
"down_sample": 0.001, # Voxel downsample for faster computation / clustering
"eps": 0.01,
"cluster_merge_distance": 0.04, # Merge distance for small clusters
"minimum_size_factor": 0.3,
"min_samples": 100, # Min cluster point size
'template_path': './clustering/apple_template.ply', # Template apple /fruit
'apple_template_size': 0.7, # Scale apple template if no gt size is available
'gt_cluster': "/path/2/gt/mesh/fruits.obj", # or None
"gt_count": 283 # or None
}。
**I would like to ask how to obtain " 'template_path': './clustering/apple_template.ply'". Can you explain in detail?**

**Comment by meyerls** [comment]
Oh yes, I forgot to upload the template meshes. I will fix this right now

**Comment by cwh01** [comment]
hello,Whether the problem is solved?
