### ISSUE TITLE
Import error with viser

### ISSUE THREAD

**Issue by victorbayonamarchal** [meyerls/FruitNeRF#14]
I try following the installations steps as described in readme. I follow the link instructions up to the tiny cuda step and then on the readme itself, installing the mentioned nerfstudio version. After that, I've followed cloning the repo and installing the  python package. However, when installin the cli and running to test the installation I keep getting the following mistake
`               from viser import (                                                                                      
           ImportError: cannot import name 'GuiHandle' from 'viser'                                                     
           (/home/victor/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/viser/__init__.py)       `

Here's the init 
```
from ._gui_api import GuiApi as GuiApi

from ._gui_handles import (
    GuiButtonGroupHandle as GuiButtonGroupHandle,
    GuiButtonHandle as GuiButtonHandle,
    GuiDropdownHandle as GuiDropdownHandle,
    GuiEvent as GuiEvent,
    GuiFolderHandle as GuiFolderHandle,
    GuiInputHandle as GuiInputHandle,
    GuiMarkdownHandle as GuiMarkdownHandle,
    GuiPlotlyHandle as GuiPlotlyHandle,
    GuiTabGroupHandle as GuiTabGroupHandle,
    GuiTabHandle as GuiTabHandle
)

from ._icons_enum import (
    Icon as Icon,
    IconName as IconName
)

from ._notification_handle import NotificationHandle as NotificationHandle

from ._scene_api import SceneApi as SceneApi

from ._scene_handles import (
    BatchedAxesHandle as BatchedAxesHandle,
    CameraFrustumHandle as CameraFrustumHandle,
    FrameHandle as FrameHandle,
    GaussianSplatHandle as GaussianSplatHandle,
    GlbHandle as GlbHandle,
    Gui3dContainerHandle as Gui3dContainerHandle,
    ImageHandle as ImageHandle,
    LabelHandle as LabelHandle,
    MeshHandle as MeshHandle,
    MeshSkinnedBoneHandle as MeshSkinnedBoneHandle,
    MeshSkinnedHandle as MeshSkinnedHandle,
    PointCloudHandle as PointCloudHandle,
    SceneNodeHandle as SceneNodeHandle,
    SceneNodePointerEvent as SceneNodePointerEvent,
    ScenePointerEvent as ScenePointerEvent,
    TransformControlsHandle as TransformControlsHandle
)

from ._viser import (
    CameraHandle as CameraHandle,
    ClientHandle as ClientHandle,
    ViserServer as ViserServer
)

```
I tried forcing reinstall as in [https://github.com/nerfstudio-project/nerfstudio/issues/2280](https://github.com/nerfstudio-project/nerfstudio/issues/2280) but it didn't work either. Thanks in advanced for the help

**Comment by meyerls** [comment]
Please have a look at issue #4

**Comment by meyerls** [comment]
Please have a look at issue #4
