### ISSUE TITLE
get masks

### ISSUE THREAD

**Issue by cwh01** [meyerls/FruitNeRF#29]
I wonder why this step is being made. Because I didn't do this step when I was training my own dataset, the results were poor.

![Uploading edc20a03c887a9111f2a52aa2b20ef7c.png…]()

**Comment by cwh01** [comment]
![getmasks](https://github.com/user-attachments/assets/dabd39db-7f07-4a21-84f4-285f527e8cd5)

**Comment by meyerls** [comment]
Oh yes good point!

I did this for rare cases when the detection's have a size larger than 20% of the original images. As my images were taken from a certain distance I do assume the fruits are small. If you have close up images from a fruit you probably should ignore it or increase the threshold
