### ISSUE TITLE
安装nerfstdio出现的问题

### ISSUE THREAD

**Issue by CBDXS1** [meyerls/FruitNeRF#4]
你好，我是一个新手
在运行这个ns-install-cli的时候出现的问题

               from nerfstudio.viewer_beta.control_panel import ControlPanel                                            
             File                                                                                                       
           "/home/zc107552403943/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/viewer_               
           beta/control_panel.py", line 23, in <module>                                                                 
               from nerfstudio.viewer_beta.viewer_elements import (  # ViewerButtonGroup,                               
             File                                                                                                       
           "/home/zc107552403943/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/viewer_               
           beta/viewer_elements.py", line 25, in <module>                                                               
               from viser import (                                                                                      
           ImportError: cannot import name 'GuiHandle' from 'viser'   
我应该怎么做，十分期待你的答复

**Comment by meyerls** [comment]
Sorry my Chinese is not that good, but I assume you have problem at the ns-install-cli step.

If you read the Readme carefully you see that you have to install **not** the latest version of nerfstudio!

From the Readme:
Important: In Section Install nerfstudio please install version 0.3.2 via pip install nerfstudio==0.3.2 not the latest one!

**Comment by CBDXS1** [comment]
> 抱歉，我的中文不太好，但我认为您在 ns-install-cli 步骤中遇到了问题。
> 
> 如果您仔细阅读自述文件，您会发现您必须安装的**不是**最新版本的nerfstudio！
> 
> 来自自述文件： 重要提示：在安装 nerfstudio 部分，请通过 pip install nerfstudio 安装版本 0.3.2==0.3.2，而不是最新版本！


Thank you very much for your answer, but this should not be the problem
![image](https://github.com/user-attachments/assets/21f277b8-5a00-4e44-a703-7130110f93f7)

**Comment by meyerls** [comment]
Oh yes my bad! I remember it was not a nerfstudio error but a viser error.

Solution:
`pip install viser==0.1.24`

**Comment by CBDXS1** [comment]
> 哦，是的，我的错！我记得这不是 nerfstudio 错误，而是 viser 错误。
> 
> 解决方案： `pip install viser==0.1.24`

ok, thank you very much and have a nice day
