### ISSUE TITLE
The 'ns process free data' command reported an error

### ISSUE THREAD

**Issue by Double-zh** [meyerls/FruitNeRF#6]
****What a great and interesting job!** 

**I am running the command 'ns protocol free data -- data/home/data/images -- output dir/home/data/FruitNeRF/output/Out1-- data_demantic/home/data/FruitNeRF/output/Out2'
”At that time, there was an error saying 'Command not found'. Did I not successfully install the environment? May I ask how to solve this problem?****

**_**_(nerfstudio) catas@catas:~/FruitNeRF$ ns-prepocess-fruit-data --data /home/catas/images --output-dir /home/catas/FruitNeRF/output/output1 --data_semantic /home/catas/FruitNeRF/output/output2**

**ns-prepocess-fruit-data：Command not found**

**(nerfstudio) catas@catas:~/FruitNeRF$ ns-train -h**
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value FruitPipelineConfig:
    _target: <class 'fruit_nerf.fruit_pipeline.FruitPipeline'>
    datamanager: FruitDataManagerConfig:
        _target: <class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>
        data: None
        camera_optimizer: CameraOptimizerConfig:
            _target: <class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>
            mode: SO3xR3
            position_noise_std: 0.0
            orientation_noise_std: 0.0
            optimizer: AdamOptimizerConfig:
                _target: <class 'torch.optim.adam.Adam'>
                lr: 0.0006
                eps: 1e-08
                max_norm: None
                weight_decay: 0.01
            scheduler: ExponentialDecaySchedulerConfig:
                _target: <class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>
                lr_pre_warmup: 1e-08
                lr_final: 6e-06
                warmup_steps: 0
                max_steps: 200000
                ramp: cosine
            param_group: camera_opt
        masks_on_gpu: None
        dataparser: FruitNerfDataParserConfig:
            _target: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>
            data: .
            scale_factor: 1.0
            downscale_factor: None
            scene_scale: 1.0
            orientation_method: up
            center_method: poses
            auto_scale_poses: True
            train_split_fraction: 0.9
        train_num_rays_per_batch: 4096
        train_num_images_to_sample_from: -1
        train_num_times_to_repeat_images: -1
        eval_num_rays_per_batch: 4096
        eval_num_images_to_sample_from: -1
        eval_num_times_to_repeat_images: -1
        eval_image_indices: [0]
        collate_fn: <function nerfstudio_collate at 0x7f32b31afca0>
        camera_res_scale_factor: 1.0
        patch_size: 1
    model: FruitNerfModelConfig:
        _target: <class 'fruit_nerf.fruit_nerf.FruitModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 32768
        prompt: None
        near_plane: 0.05
        far_plane: 1000.0
        background_color: last_sample
        hidden_dim: 64
        hidden_dim_color: 64
        hidden_dim_transient: 64
        num_levels: 16
        base_res: 16
        max_res: 2048
        log2_hashmap_size: 19
        features_per_level: 2
        num_proposal_samples_per_ray: [256
        96]
        num_nerf_samples_per_ray: 48
        proposal_update_every: 5
        proposal_warmup: 5000
        num_proposal_iterations: 2
        use_same_proposal_network: False
        proposal_net_args_list: [{'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False}, {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}]
        proposal_initial_sampler: piecewise
        interlevel_loss_mult: 1.0
        distortion_loss_mult: 0.002
        orientation_loss_mult: 0.0001
        pred_normal_loss_mult: 0.001
        use_proposal_weight_anneal: True
        use_average_appearance_embedding: True
        proposal_weights_anneal_slope: 10.0
        proposal_weights_anneal_max_num_iters: 1000
        use_single_jitter: True
        predict_normals: False
        disable_scene_contraction: False
        use_gradient_scaling: False
        implementation: tcnn
        appearance_embed_dim: 32
        semantic_loss_weight: 1.0
        pass_semantic_gradients: False
        num_layers_semantic: 2
        hidden_dim_semantics: 64
        geo_feat_dim: 15 has type <class 'fruit_nerf.fruit_pipeline.FruitPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py:1066: UserWarning: Mutable type <class 'nerfstudio.data.datamanagers.base_datamanager.DataManagerConfig'> is used as a default value for `datamanager`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.data.datamanagers.base_datamanager.DataManagerConfig'> as frozen.
  warnings.warn(
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py:1066: UserWarning: Mutable type <class 'nerfstudio.models.base_model.ModelConfig'> is used as a default value for `model`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.models.base_model.ModelConfig'> as frozen.
  warnings.warn(
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_resolver.py:455: UserWarning: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerfDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>]
  warnings.warn(
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value FruitPipelineConfig:
    _target: <class 'fruit_nerf.fruit_pipeline.FruitPipeline'>
    datamanager: FruitDataManagerConfig:
        _target: <class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>
        data: None
        camera_optimizer: CameraOptimizerConfig:
            _target: <class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>
            mode: SO3xR3
            position_noise_std: 0.0
            orientation_noise_std: 0.0
            optimizer: RAdamOptimizerConfig:
                _target: <class 'torch.optim.radam.RAdam'>
                lr: 0.0006
                eps: 1e-08
                max_norm: None
                weight_decay: 0.001
            scheduler: ExponentialDecaySchedulerConfig:
                _target: <class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>
                lr_pre_warmup: 1e-08
                lr_final: None
                warmup_steps: 0
                max_steps: 10000
                ramp: cosine
            param_group: camera_opt
        masks_on_gpu: None
        dataparser: FruitNerfDataParserConfig:
            _target: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>
            data: .
            scale_factor: 1.0
            downscale_factor: None
            scene_scale: 1.0
            orientation_method: up
            center_method: poses
            auto_scale_poses: True
            train_split_fraction: 0.9
        train_num_rays_per_batch: 8192
        train_num_images_to_sample_from: -1
        train_num_times_to_repeat_images: -1
        eval_num_rays_per_batch: 4096
        eval_num_images_to_sample_from: -1
        eval_num_times_to_repeat_images: -1
        eval_image_indices: [0]
        collate_fn: <function nerfstudio_collate at 0x7f32b31afca0>
        camera_res_scale_factor: 1.0
        patch_size: 1
    model: FruitNerfModelConfig:
        _target: <class 'fruit_nerf.fruit_nerf.FruitModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 32768
        prompt: None
        near_plane: 0.05
        far_plane: 1000.0
        background_color: last_sample
        hidden_dim: 128
        hidden_dim_color: 128
        hidden_dim_transient: 64
        num_levels: 16
        base_res: 16
        max_res: 4096
        log2_hashmap_size: 21
        features_per_level: 2
        num_proposal_samples_per_ray: [512
        256]
        num_nerf_samples_per_ray: 128
        proposal_update_every: 5
        proposal_warmup: 5000
        num_proposal_iterations: 2
        use_same_proposal_network: False
        proposal_net_args_list: [{'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False}, {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}]
        proposal_initial_sampler: piecewise
        interlevel_loss_mult: 1.0
        distortion_loss_mult: 0.002
        orientation_loss_mult: 0.0001
        pred_normal_loss_mult: 0.001
        use_proposal_weight_anneal: True
        use_average_appearance_embedding: True
        proposal_weights_anneal_slope: 10.0
        proposal_weights_anneal_max_num_iters: 5000
        use_single_jitter: True
        predict_normals: False
        disable_scene_contraction: False
        use_gradient_scaling: False
        implementation: tcnn
        appearance_embed_dim: 128
        semantic_loss_weight: 1.0
        pass_semantic_gradients: False
        num_layers_semantic: 3
        hidden_dim_semantics: 128
        geo_feat_dim: 30 has type <class 'fruit_nerf.fruit_pipeline.FruitPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value FruitPipelineConfig:
    _target: <class 'fruit_nerf.fruit_pipeline.FruitPipeline'>
    datamanager: FruitDataManagerConfig:
        _target: <class 'fruit_nerf.data.fruit_datamanager.FruitDataManager'>
        data: None
        camera_optimizer: CameraOptimizerConfig:
            _target: <class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>
            mode: SO3xR3
            position_noise_std: 0.0
            orientation_noise_std: 0.0
            optimizer: RAdamOptimizerConfig:
                _target: <class 'torch.optim.radam.RAdam'>
                lr: 0.0006
                eps: 1e-08
                max_norm: None
                weight_decay: 0.001
            scheduler: ExponentialDecaySchedulerConfig:
                _target: <class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>
                lr_pre_warmup: 1e-08
                lr_final: 6e-05
                warmup_steps: 0
                max_steps: 50000
                ramp: cosine
            param_group: camera_opt
        masks_on_gpu: None
        dataparser: FruitNerfDataParserConfig:
            _target: <class 'fruit_nerf.data.fruitnerf_dataparser.FruitNerf'>
            data: .
            scale_factor: 1.0
            downscale_factor: None
            scene_scale: 1.0
            orientation_method: up
            center_method: poses
            auto_scale_poses: True
            train_split_fraction: 0.9
        train_num_rays_per_batch: 16384
        train_num_images_to_sample_from: -1
        train_num_times_to_repeat_images: -1
        eval_num_rays_per_batch: 4096
        eval_num_images_to_sample_from: -1
        eval_num_times_to_repeat_images: -1
        eval_image_indices: [0]
        collate_fn: <function nerfstudio_collate at 0x7f32b31afca0>
        camera_res_scale_factor: 1.0
        patch_size: 1
    model: FruitNerfModelConfig:
        _target: <class 'fruit_nerf.fruit_nerf.FruitModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 32768
        prompt: None
        near_plane: 0.05
        far_plane: 1000.0
        background_color: last_sample
        hidden_dim: 256
        hidden_dim_color: 256
        hidden_dim_transient: 64
        num_levels: 16
        base_res: 16
        max_res: 8192
        log2_hashmap_size: 21
        features_per_level: 2
        num_proposal_samples_per_ray: [512
        512]
        num_nerf_samples_per_ray: 64
        proposal_update_every: 5
        proposal_warmup: 5000
        num_proposal_iterations: 2
        use_same_proposal_network: False
        proposal_net_args_list: [{'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 512, 'use_linear': False}, {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 7, 'max_res': 2048, 'use_linear': False}]
        proposal_initial_sampler: piecewise
        interlevel_loss_mult: 1.0
        distortion_loss_mult: 0.002
        orientation_loss_mult: 0.0001
        pred_normal_loss_mult: 0.001
        use_proposal_weight_anneal: True
        use_average_appearance_embedding: True
        proposal_weights_anneal_slope: 10.0
        proposal_weights_anneal_max_num_iters: 5000
        use_single_jitter: True
        predict_normals: False
        disable_scene_contraction: False
        use_gradient_scaling: False
        implementation: tcnn
        appearance_embed_dim: 32
        semantic_loss_weight: 1.0
        pass_semantic_gradients: False
        num_layers_semantic: 3
        hidden_dim_semantics: 128
        geo_feat_dim: 30 has type <class 'fruit_nerf.fruit_pipeline.FruitPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
usage: ns-train [-h]
                {depth-nerfacto,dnerf,fruit_nerf,fruit_nerf_big,fruit_nerf_huge,generfacto,instant-ngp,instant-ngp-bounded,mipnerf,nerf
acto,nerfacto-big,nerfacto-huge,neus,neus-facto,phototourism,semantic-nerfw,tensorf,vanilla-nerf,volinga,in2n,in2n-small,in2n-tiny,kpla
nes,kplanes-dynamic,lerf,lerf-big,lerf-lite,nerfplayer-nerfacto,nerfplayer-ngp,tetra-nerf,tetra-nerf-original}

Train a radiance field with nerfstudio. For real captures, we recommend using the nerfacto model.

Nerfstudio allows for customizing your training and eval configs from the CLI in a powerful way, but there are some things to 
understand.

The most demonstrative and helpful example of the CLI structure is the difference in output between the following commands:

    ns-train -h
    ns-train nerfacto -h nerfstudio-data
    ns-train nerfacto nerfstudio-data -h

In each of these examples, the -h applies to the previous subcommand (ns-train, nerfacto, and nerfstudio-data).

In the first example, we get the help menu for the ns-train script. In the second example, we get the help menu for the nerfacto model.
In the third example, we get the help menu for the nerfstudio-data dataparser.

With our scripts, your arguments will apply to the preceding subcommand in your command, and thus where you put your arguments matters!
Any optional arguments you discover from running

    ns-train nerfacto -h nerfstudio-data

need to come directly after the nerfacto subcommand, since these optional arguments only belong to the nerfacto subcommand:

    ns-train nerfacto {nerfacto optional args} nerfstudio-data

╭─ options ───────────────────────────────────────────────────────╮ ╭─ subcommands ───────────────────────────────────────────────────╮
│ -h, --help        show this help message and exit               │ │ {depth-nerfacto,dnerf,fruit_nerf,fruit_nerf_big,fruit_nerf_hug… │
╰─────────────────────────────────────────────────────────────────╯ │     depth-nerfacto                                              │
                                                                    │                   Nerfacto with depth supervision.              │
                                                                    │     dnerf         Dynamic-NeRF model. (slow)                    │
                                                                    │     fruit_nerf    Base config for FruitNeRF                     │
                                                                    │     fruit_nerf_big                                              │
                                                                    │                   Base config for FruitNeRF-Big                 │
                                                                    │     fruit_nerf_huge                                             │
                                                                    │                   Base config for FruitNeRF-Huge                │
                                                                    │     generfacto    Generative Text to NeRF model                 │
                                                                    │     instant-ngp   Implementation of Instant-NGP. Recommended    │
                                                                    │                   real-time model for unbounded scenes.         │
                                                                    │     instant-ngp-bounded                                         │
                                                                    │                   Implementation of Instant-NGP. Recommended    │
                                                                    │                   for bounded real and synthetic scenes         │
                                                                    │     mipnerf       High quality model for bounded scenes. (slow) │
                                                                    │     nerfacto      Recommended real-time model tuned for real    │
                                                                    │                   captures. This model will be continually      │
                                                                    │                   updated.                                      │
                                                                    │     nerfacto-big                                                │
                                                                    │     nerfacto-huge                                               │
                                                                    │     neus          Implementation of NeuS. (slow)                │
                                                                    │     neus-facto    Implementation of NeuS-Facto. (slow)          │
                                                                    │     phototourism  Uses the Phototourism data.                   │
                                                                    │     semantic-nerfw                                              │
                                                                    │                   Predicts semantic segmentations and filters   │
                                                                    │                   out transient objects.                        │
                                                                    │     tensorf       tensorf                                       │
                                                                    │     vanilla-nerf  Original NeRF model. (slow)                   │
                                                                    │     volinga       Real-time rendering model from Volinga.       │
                                                                    │                   Directly exportable to NVOL format at         │
                                                                    │                   https://volinga.ai/                           │
                                                                    │     in2n          [External] Instruct-NeRF2NeRF. Full model,    │
                                                                    │                   used in paper                                 │
                                                                    │     in2n-small    [External] Instruct-NeRF2NeRF. Half precision │
                                                                    │                   model                                         │
                                                                    │     in2n-tiny     [External] Instruct-NeRF2NeRF. Half prevision │
                                                                    │                   with no LPIPS                                 │
                                                                    │     kplanes       [External] K-Planes model tuned to static     │
                                                                    │                   blender scenes                                │
                                                                    │     kplanes-dynamic                                             │
                                                                    │                   [External] K-Planes model tuned to dynamic    │
                                                                    │                   DNeRF scenes                                  │
                                                                    │     lerf          [External] LERF with OpenCLIP ViT-B/16, used  │
                                                                    │                   in paper                                      │
                                                                    │     lerf-big      [External] LERF with OpenCLIP ViT-L/14        │
                                                                    │     lerf-lite     [External] LERF with smaller network and less │
                                                                    │                   LERF samples                                  │
                                                                    │     nerfplayer-nerfacto                                         │
                                                                    │                   [External] NeRFPlayer with nerfacto backbone  │
                                                                    │     nerfplayer-ngp                                              │
                                                                    │                   [External] NeRFPlayer with                    │
                                                                    │                   instang-ngp-bounded backbone                  │
                                                                    │     tetra-nerf    [External] Tetra-NeRF. Different sampler -    │
                                                                    │                   faster and better                             │
                                                                    │     tetra-nerf-original                                         │
                                                                    │                   [External] Tetra-NeRF. Official               │
                                                                    │                   implementation from the paper                 │
**Segmentation Fault (core dumped)**

**Comment by meyerls** [comment]
The command `ns protocol free data` is not available. But it is strange that `ns-process-fruit-data` is not found. 

As a quick hack you can simply try to run the file `python debug/process_data.py` and parse the same arguments.

**Comment by Double-zh** [comment]
Hello. I followed your instructions and got the following error.

**(nerfstudio) catas@catas:~/FruitNeRF$ python debug/process_data.py  --data /home/catas/FruitNeRF/images/teaser_github.mp4 --output-dir /home/catas/FruitNeRF/output3/output1 --data_semantic /home/catas/FruitNeRF/output3/output2**
['/home/catas/FruitNeRF/debug', '/home/catas/realsense_catkin_ws/devel/lib/python2.7/dist-packages', '/home/catas/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/melodic/lib/python2.7/dist-packages', '/home/catas/anaconda3/envs/nerfstudio/lib/python38.zip', '/home/catas/anaconda3/envs/nerfstudio/lib/python3.8', '/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/lib-dynload', '/home/catas/.local/lib/python3.8/site-packages', '/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages', '__editable__.fruit_nerf-0.0.1.finder.__path_hook__', '/home/catas/FruitNeRF/segmentation/grounded_sam/segment_anything']
/home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py:330: UserWarning: The field segmentation_class is annotated with type <class 'str'>, but the default value None has type <class 'NoneType'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
[23:51:16] 💀 No usable images in the data folder.                                             process_data_utils.py:309
Segmentation Fault (core dumped)

**Comment by Double-zh** [comment]
The same error still occurred.
(nerfstudio) catas@catas:~/FruitNeRF$ ns-prepocess-fruit-data --data /home/catas/images --output-dir /home/catas/FruitNeRF/output3/output1 --data_semantic /home/catas/FruitNeRF/output3/output2
**ns-prepocess-fruit-data：未找到命令**

(nerfstudio) catas@catas:~/FruitNeRF$ ns-install-cli
[23:58:04] 🔍 Detected conda environment /home/catas/anaconda3/envs/nerfstudio!                           install.py:364
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-install-cli.                                                                                     
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-dev-test.                                                                                         
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-install-cli.                                                                                      
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-dev-test.                                                                                        
[23:58:05] ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-dev-sync-viser-message-defs.                                                                      
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-process-data.                                                                                     
[23:58:06] ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-dev-sync-viser-message-defs.                                                                     
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-download-data.                                                                                   
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-download-data.                                                                                    
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-process-data.                                                                                    
[23:58:08] ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-viewer.                                                                                          
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-eval.                                                                                             
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-viewer.                                                                                           
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-render.                                                                                           
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-render.                                                                                          
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-eval.                                                                                            
[23:58:09] ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-train.                                                                                           
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-train.                                                                                            
[23:58:10] ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/bash/_ns-export.                                                                                          
           ✔ Nothing to do for                                                                            install.py:139
           /home/catas/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/completio               
           ns/zsh/_ns-export.                                                                                           
           **🙆 Completions installed to /home/catas/anaconda3/envs/nerfstudio. Cool! Reactivate the        install.py:275
           environment to try them out.                                                                                 
All done!**

**Comment by meyerls** [comment]
I found two issues relating your problem.

1. Processing data includes only images and no video (you tried a mp4). In the original nerfstudio implementation you can also pose the images in the video. But our implementations supports only images.

2. The images/teaser_github.mp4 video does not work for the reconstruction. It is a low resolution video and counting different modalities such as segmentation heat maps and binary masks. If you want to try out FruitNeRF I highly recommend you to look at the Dataset we provide. You can find the in the Readme or here: [https://zenodo.org/records/10869455](https://zenodo.org/records/10869455)

**Comment by FavorMylikes** [comment]
@Double-zh That should be a typo, `ns-prepocess-fruit-data` should be `ns-process-fruit-data`
