### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 5204AIO** [meyerls/FruitNeRF#7]
Thank you very much for sharing the project. I ran into a problem when trying to reproduce your project, which was feasible when I was training with the dataset provided by Nerfstudio, and I had this problem with your dataset instead, as shown in the image below.As a beginner in this field, I look forward to hearing from you, thank you very much.
![微信图片_20240820101018](https://github.com/user-attachments/assets/8032c205-4793-468d-b722-213ccf6c0d89)
![image](https://github.com/user-attachments/assets/70b4af5a-811b-43c1-b505-e5c310af9dae)

**Comment by meyerls** [comment]
Hi,

I am not sure what you typed in as a text prompt but it seems as _fruit_nerf_ is not listed. I would assume that you have not installed it correctly. Please follow the instruction for nerfstudio **and** fruit nerf precisely as it is explained in the Readme file.

**Comment by 5204AIO** [comment]
Thanks for the reply, my problem has been solved.

**Comment by 5204AIO** [comment]
> Hi,
> 
> I am not sure what you typed in as a text prompt but it seems as _fruit_nerf_ is not listed. I would assume that you have not installed it correctly. Please follow the instruction for nerfstudio **and** fruit nerf precisely as it is explained in the Readme file.

Problems encountered when starting training，It stops at this place, how do I fix this

**Comment by 5204AIO** [comment]
![Uploading 屏幕截图 2024-08-21 132214.png…]()

**Comment by 5204AIO** [comment]
ok ,I have completed the project, thanks for sharing
