### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by CBDXS1** [meyerls/FruitNeRF#8]
![image](https://github.com/user-attachments/assets/994591c1-ad00-48db-9603-fce6c00f10ef)
The problem I encountered during training was that I trained normally at the beginning and there was no problem with window forwarding and viewing, but then an error occurred.

![image](https://github.com/user-attachments/assets/ea8318a5-17b8-4e7e-8ecc-f31a847528a4)
Hope to get your guidance

**Comment by CBDXS1** [comment]
是因为pytorch版本问题吗

**Comment by meyerls** [comment]
I have no idea where this error comes from. It would be nice if you could give me more information on what you used as an prompt, what pytorch version you are using, what Cuda version have you installed etc. 

My first guess would be that this error originates from pytorch directly. You where talking about window forwarding and viewing. What do you mean with this?

**Comment by CBDXS1** [comment]
![image](https://github.com/user-attachments/assets/61bb12b7-7fe5-4901-9ca6-5a4a7b3990e6)

This is my pytorch and cuda version.The reason for talking about forwarding windows and viewing is that I thought there would be no version issues at this step.I run this prompt
ns-train fruit_nerf --data {path/to/workspace-dir} --output-dir {path/to/output-dir}

> 我不知道这个错误是从哪里来的。如果您能提供更多信息，比如您使用的提示符是什么、您使用的 pytorch 版本是什么、您安装的 Cuda 版本是什么等，那就太好了。
> 
> 我的第一个猜测是这个错误直接源自 pytorch。你在谈论窗口转发和查看。你的意思是什么？

**Comment by CBDXS1** [comment]
>>> import torch

>>> print("PyTorch version:", torch.__version__)
PyTorch version: 2.1.2
>>> 
>>> print("Is CUDA available:", torch.cuda.is_available())
Is CUDA available: True
>>> 
>>> print("CUDA version used by PyTorch:", torch.version.cuda)
CUDA version used by PyTorch: 12.1
>>> 
I changed the pytorch version to 2.1.2, but it still didn't work

**Comment by meyerls** [comment]
> ![image](https://private-user-images.githubusercontent.com/85206214/359847107-61bb12b7-7fe5-4901-9ca6-5a4a7b3990e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjI4MDUsIm5iZiI6MTcyNDMyMjUwNSwicGF0aCI6Ii84NTIwNjIxNC8zNTk4NDcxMDctNjFiYjEyYjctN2ZlNS00OTAxLTljYTYtNWE0YTdiMzk5MGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzBiZTBmMThlMDVhNWJhYzYwODVmYmZlZWVjYzM0Njg5ODk3MzE0ZDkzZjA3N2FkODAwNjA4YTdjZmM5ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_8BYPxwwTStPH2PO5Z4bnb6Cet2Q0P9-1dw7SU_MnA)
> 
> This is my pytorch and cuda version.The reason for talking about forwarding windows and viewing is that I thought there would be no version issues at this step.I run this prompt ns-train fruit_nerf --data {path/to/workspace-dir} --output-dir {path/to/output-dir}
> 
> > 我不知道这个错误是从哪里来的。如果您能提供更多信息，比如您使用的提示符是什么、您使用的 pytorch 版本是什么、您安装的 Cuda 版本是什么等，那就太好了。
> > 我的第一个猜测是这个错误直接源自 pytorch。你在谈论窗口转发和查看。你的意思是什么？

What path at the prompt did you parse exactly?

**Comment by CBDXS1** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/85206214/359847107-61bb12b7-7fe5-4901-9ca6-5a4a7b3990e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjI4MDUsIm5iZiI6MTcyNDMyMjUwNSwicGF0aCI6Ii84NTIwNjIxNC8zNTk4NDcxMDctNjFiYjEyYjctN2ZlNS00OTAxLTljYTYtNWE0YTdiMzk5MGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzBiZTBmMThlMDVhNWJhYzYwODVmYmZlZWVjYzM0Njg5ODk3MzE0ZDkzZjA3N2FkODAwNjA4YTdjZmM5ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_8BYPxwwTStPH2PO5Z4bnb6Cet2Q0P9-1dw7SU_MnA)
> > 这是我的pytorch和cuda版本。之所以说转发窗口和查看，是因为我觉得这一步不会有版本问题。我运行这个提示ns-train fruit_nerf --data {path/to/workspace-dir} --output-dir {path/to/output-dir}
> > > 我不知道这个错误是从哪里来的。如果您能提供更多信息，比如您使用的提示符是什么、您使用的 pytorch 版本是什么、您安装的 Cuda 版本是什么等，那就太好了。
> > > 我的第一个猜测是这个错误直接来自pytorch。你在谈论广播转发和查看。你的意思是什么？
> 
> 您具体解析了提示中的哪条路径？

ns-train fruit_nerf --data /home/zc107552403943/FruitNeRF/FruitNeRF_Dataset/tree_01 --output-dir /home/zc107552403943/FruitNeRF/output --viewer.websocket-port 8080
This is what I tried, I'm not sure if it's right

**Comment by Susango** [comment]
Hello, I also encountered the same error. My torch and cuda versions are: 2.1.2+cu118.

**Comment by meyerls** [comment]
I dont know if it fixes you problem as I cant reproduce the error but have you tried setting 
```   
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```
in `fruit_nerf/fruit_pipeline.py` at the top as it is suggested in the error?

**Comment by Susango** [comment]
> I dont know if it fixes you problem as I cant reproduce the error but have you tried setting
> 
> ```
> import torch._dynamo
> torch._dynamo.config.suppress_errors = True
> ```
> 
> in `fruit_nerf/fruit_pipeline.py` at the top as it is suggested in the error?
> 
> If it does not work please try out to downgrade to **Cuda 1.7** and **Torch 2.0.1+cu117**. These are the version FruitNeRF was developed under.

The problem has been solved, thanks!

**Comment by meyerls** [comment]
Great! What was the issue?

**Comment by CBDXS1** [comment]
> 太棒了！问题解决了吗？
Solved！！！！！ thank you very much for your guidance！

**Comment by CBDXS1** [comment]
> 太棒了！问题解决了吗？


to me. It helped a lot！
